# Alpha diversity

```{r load_data_alpha}
load("data/data.Rdata")
```

```{r alpha_div, comment="", message=FALSE, warning=FALSE}
# Calculate Hill numbers
richness <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 0) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(richness = 1) %>%
  rownames_to_column(var = "sample")

neutral <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(neutral = 1) %>%
  rownames_to_column(var = "sample")

#remove MAGs not present in the filtered table from the tree
count_table_names <- genome_counts_filt$genome
tree_tip_labels <- genome_tree$tip.label
missing_in_table <- setdiff(tree_tip_labels, count_table_names)
genome_tree_pruned <- tidytree::drop.tip(genome_tree, missing_in_table)

phylogenetic <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1, tree = genome_tree_pruned) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(phylogenetic = 1) %>%
  rownames_to_column(var = "sample")
```

```{r func_alpha_div, comment="", message=FALSE, warning=FALSE}
# Aggregate basal GIFT into elements
genome_counts_filt <- genome_counts_filt[genome_counts_filt$genome %in% rownames(genome_gifts),] 
rownames(genome_counts_filt) <- NULL
genome_gifts <- genome_gifts[rownames(genome_gifts) %in% genome_counts_filt$genome,]

dist <- genome_gifts %>%
  to.elements(., GIFT_db) %>%
  traits2dist(., method = "gower")

functional <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1, dist = dist) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(functional = 1) %>%
  rownames_to_column(var = "sample") %>%
  mutate(functional = if_else(is.nan(functional), 1, functional))
```

## Mean and standard deviation
```{r merge_alpha_div, comment="", message=FALSE, warning=FALSE}
# Merge all metrics
alpha_div_meta <- richness %>%
  full_join(neutral, by = join_by(sample == sample)) %>%
  full_join(phylogenetic, by = join_by(sample == sample)) %>%
  full_join(functional, by = join_by(sample == sample)) %>% 
  left_join(., sample_metadata, by = join_by(sample == sample))

alpha_div <- richness %>%
  full_join(neutral, by = join_by(sample == sample)) %>%
  full_join(phylogenetic, by = join_by(sample == sample)) %>%
  full_join(functional, by = join_by(sample == sample))

#By region
richness_mean <- alpha_div_meta %>%
  group_by(region) %>%
  dplyr::summarise_at(.vars = names(.)[2], .funs = c("Richness mean" = "mean", "Richness sd" = "sd"))

neutral_mean <- alpha_div_meta %>%
  group_by(region) %>%
  dplyr::summarise_at(.vars = names(.)[3], .funs = c("Neutral mean" = "mean", "Neutral sd" = "sd"))

phylogenetic_mean <- alpha_div_meta %>%
  group_by(region) %>%
  dplyr::summarise_at(.vars = names(.)[4], .funs = c("Phylogenetic mean" = "mean", "Phylogenetic sd" = "sd"))

functional_mean <- alpha_div_meta %>%
  group_by(region) %>%
  dplyr::summarise_at(.vars = names(.)[5], .funs = c("Functional mean" = "mean", "Functional sd" = "sd"))

cbind(richness_mean, neutral_mean[, 2:3], phylogenetic_mean[, 2:3], functional_mean[, 2:3])
```

## Diversity plots
```{r alpha_div_plot1, comment="", message=FALSE, warning=FALSE}
alpha_div_pivot <- richness %>%
  full_join(neutral,by=join_by(sample==sample)) %>%
  full_join(phylogenetic,by=join_by(sample==sample)) %>%
  full_join(functional,by=join_by(sample==sample)) %>%
  pivot_longer(-sample, names_to = "data", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample))

alpha_div_pivot %>%
  ggplot(aes(x=value, y=sample)) +
  geom_bar(stat='identity', fill="#6c9ebc") +
  facet_nested(region ~ data,  scales="free")+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(strip.background = element_blank(),
    panel.grid.minor.x = element_line( size=.1, color="grey" ),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r alpha_div_rich_plot, comment="", echo=FALSE, message=FALSE, warning=FALSE}
plot1 <- alpha_div %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(x = region, y = richness, group = region, color = region, fill = region)) +
      geom_boxplot(width = 0.5, outlier.shape = NA, show.legend = FALSE) +
      geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
 stat_compare_means(label.x = 1.2, 
                     label.y = 10,
                    show.legend = FALSE)+
      scale_color_manual(name="Region",
          values=c("#e5bd5b", "#6b7398")) +
      scale_fill_manual(name="Region",
          values=c("#e5bd5b50", "#6b739850")) +
  theme(axis.text.x = element_text(vjust = 0.5),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(face = "bold", size = 12),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
    panel.background = element_blank(),
    # panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black")) +
  guides(colour = guide_legend(override.aes = list(size = 6))) +
  labs(x = NULL, y = "Richness")
```

```{r alpha_div_neutral, comment="", echo=FALSE, message=FALSE, warning=FALSE}
plot2 <- alpha_div %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(x = region, y = neutral, group = region, color = region, fill = region)) +
      geom_boxplot(width = 0.5, outlier.shape = NA, show.legend = FALSE) +
      geom_jitter(width = 0.2, alpha=0.5, show.legend = FALSE) +
 stat_compare_means(label.x = 1.2, 
                     label.y = 10,
                    show.legend = FALSE)+
      scale_color_manual(name="Region",
          values=c("#e5bd5b", "#6b7398")) +
      scale_fill_manual(name="Region",
          values=c("#e5bd5b50", "#6b739850")) +
  theme(axis.text.x = element_text(vjust = 0.5),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(face = "bold", size = 12),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
    panel.background = element_blank(),
    # panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black")) +
  guides(colour = guide_legend(override.aes = list(size = 6))) +
  labs(x = NULL, y = "Neutral")
```

```{r alpha_div_phylo, comment="", echo=FALSE, message=FALSE, warning=FALSE}
plot3 <- alpha_div %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(x = region, y = phylogenetic, group = region, color = region, fill = region)) +
  geom_boxplot(width = 0.5, outlier.shape = NA, show.legend = FALSE) +
  geom_jitter(width = 0.2, alpha = 0.5, show.legend = FALSE) +
   stat_compare_means(label.x = 1.2, 
                     label.y = 10,
                    show.legend = FALSE) +
  annotate(
    "text", x = 2.3, y = 10.1, # corrected position of * on print figure
    label = "*", size = 6, fontface = "bold") +
  scale_color_manual(name = "Region",
    values = c("#e5bd5b", "#6b7398")) +
  scale_fill_manual(name = "Region",
    values = c("#e5bd5b50", "#6b739850")) +
  theme(
    axis.text.x = element_text(vjust = 0.5),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(face = "bold", size = 12),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black")
  ) +
  guides(colour = guide_legend(override.aes = list(size = 6))) +
  labs(x = NULL, y = "Phylogenetic")
```

```{r alpha_div_func, comment="", echo=FALSE, message=FALSE, warning=FALSE}
plot4 <- alpha_div %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(x = region, y = functional, group = region, color = region, fill = region)) +
      geom_boxplot(width = 0.5, outlier.shape = NA, show.legend = FALSE) +
      geom_jitter(width = 0.2, alpha=0.5,show.legend = FALSE) +
    annotate("text", x = 1.72, y = 1.63,  # Adjusted for the ylim range
           label = "*", size = 6, fontface = "bold") +
 stat_compare_means(label.x = 1.2, 
                     label.y = 1.625,
                    show.legend = FALSE)+
      scale_color_manual(name="Region",
          values=c("#e5bd5b", "#6b7398")) +
      scale_fill_manual(name="Region",
          values=c("#e5bd5b50", "#6b739850")) + 
        ylim(1.2,1.63)+
  theme(axis.text.x = element_text(vjust = 0.5),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(face = "bold", size = 12),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
    panel.background = element_blank(),
    # panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black")) +
  guides(colour = guide_legend(override.aes = list(size = 6)))+
  labs(x = NULL, y = "Functional")
```

```{r div_plot_together, comment="", echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width=10, fig.fullwidth=TRUE}
grid.arrange(arrangeGrob(plot1,plot2,plot3,plot4, ncol = 2)) 
```
Graph w/o functional plot:
```{r div_plot_together_no_func, comment="", echo=FALSE, message=FALSE, warning=FALSE, fig.height=4, fig.width=10, fig.fullwidth=TRUE}
grid.arrange(arrangeGrob(plot1,plot2,plot3, ncol = 3)) 
```

## Statistical testing when significance detected via plotting
```{r}
#Phylogenetic
# Shapiro-Wilk test for normality
alpha_div_meta %>%
  dplyr::select(region, sample, phylogenetic)  %>%
  filter(region %in% c("Daneborg", "Ittoqqortoormiit")) %>%
  group_by(region) %>%
  summarise(shapiro_p = shapiro.test(phylogenetic)$p.value) -> shapiro_results_P
# Results: Daneborg = 0.5932516 Ittoqqortoormiit = 0.9877714
# Data is normally distributed, thus parametric tests may be applied

alpha_div_meta %>%
  dplyr::select(region, sample, phylogenetic) %>%
  filter(region %in% c("Daneborg", "Ittoqqortoormiit")) %>%
  bartlett.test(phylogenetic ~ region, data = .) -> bartlett_results_P
# Results: p-value = 0.006405
# Thus equal variance cannot be assumed

# T test assuming unequal variance
alpha_div_meta %>%
  select(region, sample, phylogenetic) %>%
  filter(region %in% c("Daneborg", "Ittoqqortoormiit")) %>%
  group_by(region) %>%
  summarise(
    t_test_p = t.test(phylogenetic ~ region, data = ., var.equal = FALSE)$p.value,
    W_score = t.test(phylogenetic ~ region, data = ., var.equal = FALSE)$statistic
  ) -> t_test_results_P
# Results: p= 0.009434883; W = -2.711391	

# Wilcoxon
alpha_div_meta %>%
  select(region, sample, phylogenetic) %>%
  filter(region %in% c("Daneborg", "Ittoqqortoormiit")) %>%
  group_by(region) %>%
  summarise(
    wilcox_p = wilcox.test(phylogenetic ~ region, data = .)$p.value,
    W_statistic = wilcox.test(phylogenetic ~ region, data = .)$statistic
  ) -> wilcox_results
# Results: p= 0.006481063	, W = 247
```
```{r}
#Functional
# Shapiro-Wilk test for normality
alpha_div_meta %>%
  dplyr::select(region, sample, functional)  %>%
  filter(region %in% c("Daneborg", "Ittoqqortoormiit")) %>%
  group_by(region) %>%
  summarise(shapiro_p = shapiro.test(functional)$p.value) -> shapiro_results_F
# Results: Daneborg = 7.498381e-09 Ittoqqortoormiit = 2.627117e-03	
# Data is not normally distributed

# Wilcoxon
alpha_div_meta %>%
  select(region, sample, functional) %>%
  filter(region %in% c("Daneborg", "Ittoqqortoormiit")) %>%
  group_by(region) %>%
  summarise(
    wilcox_f = wilcox.test(functional ~ region, data = .)$p.value,
    W_statistic = wilcox.test(functional ~ region, data = .)$statistic
  ) -> wilcox_results_F
# Results: p=0.0001328166	, W = 182	
```

```

