# Differential abundance analysis: taxonomic

```{r load_data_tax, comment="", echo=FALSE, message=FALSE, warning=FALSE}
load("data/data.Rdata")
```

## Structural zeros
```{r zero, comment="", echo=FALSE, message=FALSE, warning=FALSE}
Ittoq_samples <- sample_metadata %>% 
                    filter(region == "Ittoqqortoormii") %>% 
                    dplyr::select(sample) %>% pull()

daneb_samples <- sample_metadata %>% 
                    filter(region == "Daneborg") %>% 
                    dplyr::select(sample) %>% pull()

structural_zeros <- genome_counts_filt %>% 
   rowwise() %>% #compute for each row (genome)
   mutate(all_zeros_Ittoq = all(c_across(all_of(Ittoq_samples)) == 0)) %>% # set true if all samples in TJ1 have zeros
   mutate(all_zeros_daneb = all(c_across(all_of(daneb_samples)) == 0)) %>% # set true if all samples in TJ2 have zeros
   mutate(average_Ittoq = mean(c_across(all_of(Ittoq_samples)), na.rm = TRUE)) %>% # get average genome counts across TJ1
   mutate(average_daneb = mean(c_across(all_of(daneb_samples)), na.rm = TRUE)) %>% # get average genome counts across TJ2
   filter(all_zeros_Ittoq == TRUE || all_zeros_daneb==TRUE)  %>% # filter only genomes with structural zeros
   mutate(present = case_when(
      all_zeros_Ittoq & !all_zeros_daneb ~ "daneb",
      !all_zeros_Ittoq & all_zeros_daneb ~ "Ittoq",
      !all_zeros_Ittoq & !all_zeros_daneb ~ "None",
      TRUE ~ NA_character_
    )) %>%
   mutate(average = ifelse(present == "Ittoq", average_Ittoq, average_daneb)) %>%
   dplyr::select(genome, present, average) %>%
   dplyr::left_join(genome_metadata, by=join_by(genome==genome)) %>%
   dplyr::arrange(present,-average)
```

```{r zero_plot, comment="", echo=FALSE, message=FALSE, warning=FALSE}
#Get phylum colors from the EHI standard
phylum_colors <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
  mutate_at(vars(phylum), ~ str_replace(., "[dpcofgs]__", "")) %>%
  right_join(structural_zeros, by=join_by(phylum == phylum)) %>%
    arrange(match(genome, genome_tree$tip.label)) %>%
    dplyr::select(phylum, colors) %>%
    mutate(colors = str_c(colors, "80"))  %>% #add 80% alpha
    unique() %>%
    arrange(phylum) %>%
    dplyr::select(colors) %>%
    pull()

structural_zeros %>%
    mutate(average = ifelse(present == "Ittoq", average * -1, average)) %>%
    ggplot(., aes(x=average, y=forcats::fct_rev(phylum), color=phylum)) +
      geom_jitter(height = 0.01, size=3) +
      geom_vline(xintercept=0) + 
      xlim(-max(structural_zeros$average)-3,max(structural_zeros$average)+3) +
      scale_color_manual(values=phylum_colors) +
      geom_text(aes(-100, 1), label = "Only present\nin Ittoqqortoormiit", color="#666666") +
      geom_text(aes(100, 1), label = "Only present\nin Daneborg", color="#666666") +
     theme(legend.position='none',
          panel.background = element_blank(),
          axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"))+
      labs(y="Genus",x="Genome counts") + 
      guides(col=guide_legend("Phylum"))
```
```{r zero_phylo, comment="", echo=FALSE, message=FALSE, warning=FALSE}
#phyloseq object considering structual zeros
phylo_samples <- sample_metadata %>% 
                    column_to_rownames("sample") %>% 
                    sample_data() #convert to phyloseq sample_data object
phylo_genome <- genome_counts_filt %>% 
                    filter(!genome %in% structural_zeros$genome) %>% # remove structural zeros
                    column_to_rownames("genome") %>% 
                    mutate_all(~ replace(., . == 0, 0.00001)) %>% #add pseudo counts to avoid structural zero issues (note this approach can be improved!)
                    otu_table(., taxa_are_rows = TRUE)
phylo_taxonomy <- genome_metadata %>% 
                    filter(genome %in% rownames(phylo_genome)) %>% # remove structural zeros
                    mutate(genome2=genome) %>% #create a pseudo genome name column
                    column_to_rownames("genome2") %>% 
                    dplyr::select(domain,phylum,class,order,family,genus,species,genome) %>% #add an additional taxonomic level to ensure genome-level analysis (as no all genomes have species-level taxonomic assignments. Otherwise, ANCOMBC2 aggregates analyses per species)
                    as.matrix() %>% 
                    tax_table() #convert to phyloseq tax_table object

physeq_genome_filtered <- phyloseq(phylo_genome, phylo_taxonomy, phylo_samples)
```

## Ancombc2 (considering structural zeros): Mag level
```{r ancom_rand, comment="", echo=FALSE, message=FALSE, warning=FALSE}
set.seed(1234) #set seed for reproducibility
ancom_rand_output = ancombc2(data = physeq_genome_filtered, 
                  assay_name = "counts",
                  tax_level = NULL, #change to agglomerate analysis to a higher taxonomic range
                  fix_formula = "region", #fixed variable(s)
#                  rand_formula = "(1|Individual)",
                  p_adj_method = "holm", 
                  pseudo_sens = TRUE,
                  prv_cut = 0, 
                  s0_perc = 0,
                  group = NULL, 
                  struc_zero = FALSE, 
                  neg_lb = FALSE,
                  alpha = 0.05, 
                  n_cl = 2, 
                  verbose = TRUE,
                  global = FALSE, 
                  pairwise = FALSE, 
                  dunnet = FALSE, 
                  trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = NULL,
                  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100), 
                  trend_control = NULL)
```
```{r ancom_rand_res, comment="", echo=FALSE,message=FALSE, warning=FALSE}
taxonomy <- data.frame(physeq_genome_filtered@tax_table) %>%
  rownames_to_column(., "taxon") %>%
  mutate_at(vars(phylum, genus), ~ str_replace(., "[dpcofgs]__", ""))

ancombc_rand_table <- ancom_rand_output$res %>%
  dplyr::select(taxon, lfc_regionIttoqqortoormii, p_regionIttoqqortoormii) %>%
  filter(p_regionIttoqqortoormii < 0.05) %>%
  dplyr::arrange(p_regionIttoqqortoormii) %>%
  merge(., taxonomy, by="taxon")

colors_alphabetic <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
  mutate_at(vars(phylum), ~ str_replace(., "[dpcofgs]__", ""))  %>%
  right_join(taxonomy, by=join_by(phylum == phylum)) %>%
  dplyr::select(phylum, colors) %>%
  mutate(colors = str_c(colors, "80"))  %>% #add 80% alpha
	unique() %>%
	dplyr::arrange(phylum)

tax_table <- as.data.frame(unique(ancombc_rand_table$phylum))
colnames(tax_table)[1] <- "phylum"
tax_color <- merge(tax_table, colors_alphabetic, by="phylum")%>%
	dplyr::arrange(phylum) %>%
	dplyr::select(colors) %>%
	pull()
```

```{r ancombc_rand_plot, comment="", echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width=10, fig.fullwidth=TRUE}
ggplot(ancombc_rand_table, aes(x=forcats::fct_rev(genus), y=lfc_regionIttoqqortoormii, color=phylum)) + 
  geom_point(size=4) + 
  scale_color_manual(values=tax_color) + 
  geom_hline(yintercept=0) + 
  coord_flip()+
  theme(axis.text = element_text(size = 10, face="bold.italic"),
        axis.title = element_text(size = 12),
        legend.position = "right", 
        legend.title = element_blank(),
        panel.background = element_blank(),
          panel.grid.major = element_line(size = 0.15, linetype = 'solid',
                                colour = "grey"))+
  xlab("Genus") + 
  ylab("log2FoldChange")+
  guides(col=guide_legend("Phylum"))
```
```{r ancom_rand_volcano, comment="", message=FALSE, warning=FALSE}
ancom_result <- ancom_rand_output$res %>%
  na.omit() %>%
  dplyr::rename(genome=taxon) %>%
  left_join(genome_metadata,by=join_by(genome==genome))
ancom_result %>%
    mutate(significance = ifelse(p_regionIttoqqortoormii < 0.05, "1", "0")) %>%
    ggplot(., aes(x=-log(p_regionIttoqqortoormii), y=lfc_regionIttoqqortoormii, color=significance)) +
      geom_point() +
      scale_color_manual(values = c("#cccccc","#00FFFF")) +
      geom_text(aes(3, 5), label = "Enriched\nin Ittoqqortoormii", color="#666666") +
      geom_text(aes(3, -5), label = "Enriched\nin Danenborg", color="#666666") +
      labs(color="Significance", y="Difference between locations", x="p-value") +
      theme_classic()
```

## Ancombc2 (considering structural zeros): Genus level

```{r name_gen, comment="", echo=FALSE,message=FALSE, warning=FALSE}
physeq_genome_filtered_test<- physeq_genome_filtered
tax <- data.frame(tax_table(physeq_genome_filtered_test))

tax.clean <- data.frame(row.names = row.names(tax),
domain = str_replace(tax[,1], "d__",""),
phylum = str_replace(tax[,2], "D_1__",""),
class = str_replace(tax[,3], "c__",""),
order = str_replace(tax[,4], "o__",""),
family = str_replace(tax[,5], "f__",""),
genus = str_replace(tax[,6], "g__",""),
species = str_replace(tax[,7], "s__",""),
stringsAsFactors = FALSE)
tax.clean[is.na(tax.clean)] <- ""

for (i in 1:7){ tax.clean[,i] <- as.character(tax.clean[,i])}
####### Fille holes in the tax table
tax.clean[is.na(tax.clean)] <- ""
for (i in 1:nrow(tax.clean)){

#Fill in missing taxonomy
if (tax.clean[i,2] == ""){
domain <- paste("domain_", tax.clean[i,1], sep = "")
tax.clean[i, 2:7] <- domain
} else if (tax.clean[i,3] == ""){
phylum <- paste("phylum_", tax.clean[i,2], sep = "")
tax.clean[i, 3:7] <- phylum
} else if (tax.clean[i,4] == ""){
class <- paste("class_", tax.clean[i,3], sep = "")
tax.clean[i, 4:7] <- class
} else if (tax.clean[i,5] == ""){
order <- paste("order_", tax.clean[i,4], sep = "")
tax.clean[i, 5:7] <- order
} else if (tax.clean[i,6] == ""){
family <- paste("family_", tax.clean[i,5], sep = "")
tax.clean[i, 6:7] <- family
} else if (tax.clean[i,7] == ""){
tax.clean$species[i] <- paste("genus",tax.clean$genus[i], sep = "_")
}
}

tax_table(physeq_genome_filtered_test) <- as.matrix(tax.clean)


```

```{r ancom_rand_gen, comment="", echo=FALSE,message=FALSE, warning=FALSE}
ancom_rand_output_gen = ancombc2(data = physeq_genome_filtered_test, 
                  assay_name = "counts",
                  tax_level = "genus", #change to agglomerate analysis to a higher taxonomic range
                  fix_formula = "region", #fixed variable(s)
                  p_adj_method = "holm", 
                  pseudo_sens = TRUE,
                  prv_cut = 0, 
                  s0_perc = 0,
                  group = NULL, 
                  struc_zero = FALSE, 
                  neg_lb = FALSE,
                  alpha = 0.05, 
                  n_cl = 2, 
                  verbose = TRUE,
                  global = FALSE, 
                  pairwise = FALSE, 
                  dunnet = FALSE, 
                  trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = NULL,
                  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100), 
                  trend_control = NULL)
```

```{r ancom_rand_res_gen, comment="", echo=FALSE,message=FALSE, warning=FALSE}
taxonomy <- data.frame(physeq_genome_filtered@tax_table) %>%
  rownames_to_column(., "taxon") %>%
  mutate_at(vars(phylum, genus), ~ str_replace(., "[dpcofgs]__", ""))%>%
  select(phylum, genus)%>%
	unique()

ancombc_rand_table_gen <- ancom_rand_output_gen$res %>%
  mutate_at(vars(taxon), ~ str_replace(., "[dpcofgs]__", ""))%>%
  dplyr::select(taxon, lfc_regionIttoqqortoormii, p_regionIttoqqortoormii) %>%
  filter(p_regionIttoqqortoormii < 0.05) %>%
  dplyr::arrange(lfc_regionIttoqqortoormii)  %>%
  left_join(taxonomy, by=join_by(taxon == genus)) %>%
  dplyr::arrange(lfc_regionIttoqqortoormii)

colors_alphabetic <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
  mutate_at(vars(phylum), ~ str_replace(., "[dpcofgs]__", ""))  %>%
  right_join(taxonomy, by=join_by(phylum == phylum)) %>%
  dplyr::select(phylum, colors) %>%
  mutate(colors = str_c(colors, "80"))  %>% #add 80% alpha
	unique() %>%
	dplyr::arrange(phylum)

tax_table <- as.data.frame(unique(ancombc_rand_table_gen$phylum))

colnames(tax_table)[1] <- "phylum"
tax_color <- merge(tax_table, colors_alphabetic, by="phylum")%>%
	dplyr::arrange(phylum) %>%
	dplyr::select(colors) %>%
	pull()
```

```{r ancombc_rand_plot_gen, comment="", echo=FALSE,message=FALSE, warning=FALSE}
ancombc_rand_table_gen%>%
      mutate(taxon=factor(taxon,levels=ancombc_rand_table_gen$taxon)) %>%
mutate(Color = ifelse(lfc_regionIttoqqortoormii <0, "Daneborg","Ittoqqortoormii")) %>%
ggplot(., aes(x=lfc_regionIttoqqortoormii, y=forcats::fct_rev(taxon), fill=Color)) + #forcats::fct_rev()
  geom_col() + 
  scale_fill_manual(values=tax_color) + 
  geom_hline(yintercept=0) + 
#  coord_flip()+
  theme(panel.background = element_blank(),
        axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14, face = "bold"),
        legend.position = "right", legend.box = "vertical")+
  xlab("log2FoldChange") + 
  ylab("Genera")+
  guides(fill=guide_legend(title="Group"))

```

```{r ancom_rand_volcano_gen, comment="", echo=FALSE, message=FALSE, warning=FALSE}
ancom_result_gen <- ancom_rand_output_gen$res %>%
  na.omit() %>%
  dplyr::rename(genome=taxon) %>%
  left_join(genome_metadata,by=join_by(genome==genome))
ancom_result_gen %>%
    mutate(significance = ifelse(p_regionIttoqqortoormii < 0.05, "1", "0")) %>%
    ggplot(., aes(x=-log(p_regionIttoqqortoormii), y=lfc_regionIttoqqortoormii, color=significance)) +
      geom_point() +
      scale_color_manual(values = c("#cccccc","#00FFFF")) +
      geom_text(aes(3, 5), label = "Enriched\nin Ittoqqortoormii", color="#666666") +
      geom_text(aes(3, -5), label = "Enriched\nin Danenborg", color="#666666") +
      labs(color="Significance", y="Difference between locations", x="p-value") +
      theme_classic()
```


